wandb:
  project: 'Donut-finetuning'
  name: 'finetunig-cord'

model:
  model_name_or_path: "naver-clova-ix/donut-base"
  cache_dir: "./hub/model"
  image_size:
  - 1280
  - 960
  max_length: 768

data:
  dataset_name_or_path: "naver-clova-ix/cord-v2"
  cache_dir: "./hub/dataset"
  train_batch_size: 1
  val_batch_size: 1
  num_workers: 4

training:
  max_epochs: 30
  lr: !!float 3e-5
  warmup_steps: 300 # 800/8*30/10, 10%
  result_path: "./result"
  verbose: True