wandb:
  project: 'Donut-finetuning'
  name: 'finetunig-cord-TEST'
  training_info:
    purpose: 'task start token 적용'
    date: '2025-02-13'
    dataset: 'cord-v3'
    additional_info: '그동안 task start token 을 따로 지정하지 않았다. 코드 수정후 학습해본다.'

model:
  model_name_or_path: "naver-clova-ix/donut-base"
  cache_dir: "./hub/model"
  image_size:
  - 1280 # height
  - 960 # width  
  max_length: 768
  task_start_token: "<s_cord-v2>"

data:
  dataset_name_or_path: "naver-clova-ix/cord-v2"
  cache_dir: "./hub/dataset"
  train_batch_size: 2
  val_batch_size: 2
  num_workers: 4

training:
  max_epochs: 30
  lr: !!float 3e-5
  warmup_steps: 300 # 800/8*30/10, 10%
  result_path: "./result"
  verbose: false